Return promise for Android restorePurchase
PeterStaev/nativescript-purchase pull request #69
Opened 2019-03-28 19:43 UTC by interrobrian

We ran into a scenario where we wanted to know if restore purchases returned no purchases at all on Android. This doesn't get expressed through Transactions, so this pull request makes restorePurchases return its promise on Android, so that the caller can know when it's done. It still returns nothing on iOS, but you can use getStoreReceipt to do the same thing.

2019-03-28 22:00 UTC, PeterStaev requested changes
I prefer to have the API standardized across platforms. So please make the iOS method return a dummy `Promise` that immediately resolves and adjust the readme accordingly

2019-03-29 00:02 UTC, interrobrian commented
Done

2019-03-29 08:44 UTC, PeterStaev approved these changes

2019-03-30 17:10 UTC, merged

2019-03-30 21:39 UTC, PeterStaev commented
Thanks for your contribution! New version is on npm.